import type { Metadata } from "next";
import { FileJson, Blocks, Cog, Code } from "lucide-react";

export const metadata: Metadata = {
  title: "Terraform JSON Configuration Best Practices (.tf.json Provider Syntax) | Article",
  description:
    "Learn the current best practices for Terraform .tf.json files, including required_providers, provider aliases, module provider mapping, expression rules, and validation steps.",
};

export default function TerraformJsonBestPracticesArticle() {
  return (
    <>
      <h1 className="text-3xl font-bold mb-6 flex items-center">
        <FileJson className="mr-3 h-8 w-8 text-blue-500" />
        Terraform JSON Configuration File Best Practices
      </h1>

      <div className="space-y-6">
        <p>
          If you searched for Terraform JSON provider syntax, the key point is that <code>.tf.json</code> is not a
          separate Terraform feature. It is the JSON representation of normal Terraform configuration, and it works
          best when another program is generating the files for you. For infrastructure people edit directly, plain
          <code>.tf</code> remains the better default.
        </p>
        <p>
          The biggest mistakes teams make are putting provider requirements in the wrong place, confusing literal
          strings with Terraform expressions, and assuming <code>terraform fmt</code> can convert HCL into JSON. This
          guide focuses on the current behavior that matters most for real-world <code>.tf.json</code> modules.
        </p>

        <h2 className="text-2xl font-semibold mt-8 flex items-center">
          <Blocks className="mr-2 h-6 w-6 text-green-500" />
          When .tf.json Is The Right Tool
        </h2>
        <p>
          Use JSON syntax when your source of truth already lives in code, templates, a catalog, or another system
          that can emit valid JSON. Terraform loads <code>.tf</code> and <code>.tf.json</code> files together, so you
          do not need to choose one format for an entire module.
        </p>
        <ul className="list-disc pl-6 space-y-2 my-4">
          <li>
            <strong>Use .tf.json for generated configuration:</strong> It is a good target for code generators,
            scaffolding tools, or internal platforms that already work with JSON objects.
          </li>
          <li>
            <strong>Keep hand-authored modules in HCL:</strong> HCL is easier to review, comment, refactor, and debug
            when humans are changing the configuration often.
          </li>
          <li>
            <strong>Do not switch formats just because one argument needs JSON:</strong> If a provider attribute expects
            JSON text, keep the Terraform file in HCL and use <code>jsonencode()</code> for that specific value.
          </li>
        </ul>

        <h2 className="text-2xl font-semibold mt-8 flex items-center">
          <Code className="mr-2 h-6 w-6 text-purple-500" />
          Provider Syntax In .tf.json
        </h2>
        <p>
          For searchers looking for Terraform JSON configuration syntax around providers, the important split is:
          <code> terraform.required_providers </code>
          declares where providers come from, top-level <code>provider</code> blocks configure them, and resource or
          module arguments choose which configured instance to use.
        </p>

        <div className="bg-gray-100 p-4 rounded-lg dark:bg-gray-800 my-4 overflow-x-auto">
          <h3 className="text-lg font-medium">Provider-Focused .tf.json Example</h3>
          <pre>
            <code className="language-json">
              {`{
  "//": "Generated by tools/generate-terraform-json.ts",
  "terraform": {
    "required_version": ">= 1.0.0",
    "required_providers": {
      "aws": {
        "source": "hashicorp/aws",
        "version": "~> 5.0"
      }
    }
  },
  "provider": {
    "aws": [
      {
        "region": "us-east-1"
      },
      {
        "alias": "west",
        "region": "us-west-2"
      }
    ]
  },
  "resource": {
    "aws_s3_bucket": {
      "logs": {
        "provider": "aws.west",
        "bucket": "example-logs-bucket"
      }
    }
  },
  "module": {
    "network": {
      "source": "./modules/network",
      "providers": {
        "aws": "aws.west"
      }
    }
  }
}`}
            </code>
          </pre>
        </div>

        <ol className="list-decimal pl-6 space-y-3 my-4">
          <li>
            <strong>Declare provider requirements under the top-level terraform block:</strong>{" "}
            <code>required_providers</code> is where you set the provider local name, source address, and version
            constraint.
          </li>
          <li>
            <strong>Configure providers separately:</strong> The top-level <code>provider</code> object contains one or
            more provider configuration blocks. When you need multiple configurations, such as an aliased provider, the
            JSON form is an array of objects under that provider name.
          </li>
          <li>
            <strong>Use literal provider addresses when selecting an alias:</strong> Resource-level{" "}
            <code>provider</code> values and module-level <code>providers</code> mappings use strings like{" "}
            <code>aws.west</code>, not interpolation syntax.
          </li>
          <li>
            <strong>Keep provider versions out of provider configuration:</strong> Version constraints belong in{" "}
            <code>required_providers</code>, not in the provider configuration block itself.
          </li>
        </ol>

        <p>
          If you still maintain Terraform 0.12.26, it accepts the object form of <code>required_providers</code> but
          ignores the <code>source</code> setting. Current Terraform versions should use the modern object form shown
          above.
        </p>

        <h2 className="text-2xl font-semibold mt-8">Expression Rules That Trip People Up</h2>
        <p>
          JSON does not have Terraform&apos;s native expression syntax, so Terraform maps JSON values into expression
          contexts. That mapping is the main reason generated files are easy to get subtly wrong.
        </p>
        <ul className="list-disc pl-6 space-y-2 my-4">
          <li>
            <strong>In expression positions, JSON strings are parsed as Terraform string templates:</strong>{" "}
            <code>{'"web-${var.environment}"'}</code> and <code>{'"${var.instance_count}"'}</code> are both valid
            patterns inside arguments that accept Terraform expressions.
          </li>
          <li>
            <strong>If the whole string is a single interpolation, Terraform can use the underlying value type:</strong>{" "}
            that matters for numbers, booleans, lists, maps, and references passed through generated JSON.
          </li>
          <li>
            <strong>Some arguments are literal-only:</strong> Common examples are <code>terraform.required_version</code>,{" "}
            <code>required_providers.source</code>, <code>required_providers.version</code>, <code>module.source</code>,
            and provider aliases.
          </li>
          <li>
            <strong>Comments are limited but not impossible:</strong> A property named <code>"//"</code> is ignored at
            the root level and inside objects that represent block bodies, which makes it useful for generator notes.
          </li>
        </ul>

        <div className="bg-gray-100 p-4 rounded-lg dark:bg-gray-800 my-4 overflow-x-auto">
          <h3 className="text-lg font-medium">Expression Example</h3>
          <pre>
            <code className="language-json">
              {`{
  "resource": {
    "aws_instance": {
      "web": {
        "count": "\${var.instance_count}",
        "ami": "ami-0abcdef1234567890",
        "instance_type": "t3.micro",
        "tags": {
          "Name": "web-\${var.environment}"
        }
      }
    }
  }
}`}
            </code>
          </pre>
        </div>

        <h2 className="text-2xl font-semibold mt-8 flex items-center">
          <Cog className="mr-2 h-6 w-6 text-orange-500" />
          Best Practices For Maintainable .tf.json
        </h2>
        <ol className="list-decimal pl-6 space-y-3 my-4">
          <li>
            <strong>Use JSON syntax as a generation target, not a hand-editing format:</strong> If engineers need to
            review and edit the configuration daily, keep the source in HCL and generate only the parts that truly need
            JSON.
          </li>
          <li>
            <strong>Make provider requirements explicit from the start:</strong> Declare every provider in{" "}
            <code>terraform.required_providers</code>, run <code>terraform init</code>, and commit the resulting{" "}
            <code>.terraform.lock.hcl</code> when you want repeatable provider installation.
          </li>
          <li>
            <strong>Generate JSON with a real serializer:</strong> Do not assemble braces and quotes by hand. Let your
            language emit valid JSON so numbers, booleans, arrays, and escaping all stay correct.
          </li>
          <li>
            <strong>Prefer predictable output:</strong> Stable key ordering, stable file naming, and a root{" "}
            <code>"//"</code> marker make generated modules much easier to diff and review.
          </li>
          <li>
            <strong>Validate exactly the way Terraform will run:</strong> A generated file is not finished until it
            passes formatting, validation, and at least one real plan in CI.
          </li>
          <li>
            <strong>Do not rely on terraform fmt for format conversion:</strong> <code>terraform fmt</code> formats
            Terraform configuration files, including <code>.tf.json</code>, but it is not a general HCL-to-JSON or
            JSON-to-HCL converter.
          </li>
        </ol>

        <div className="bg-gray-100 p-4 rounded-lg dark:bg-gray-800 my-4 overflow-x-auto">
          <h3 className="text-lg font-medium">Practical Validation Loop</h3>
          <pre>
            <code className="language-bash">{`terraform init
terraform fmt -check -recursive
terraform validate
terraform plan`}</code>
          </pre>
        </div>

        <h2 className="text-2xl font-semibold mt-8">Common Mistakes And Troubleshooting</h2>
        <ul className="list-disc pl-6 space-y-2 my-4">
          <li>
            <strong>required_providers in the wrong place:</strong> It must live inside the top-level{" "}
            <code>terraform</code> block, not inside the top-level <code>provider</code> object.
          </li>
          <li>
            <strong>Wrong alias reference syntax:</strong> Use <code>"provider": "aws.west"</code>, not{" "}
            <code>{'"provider": "${aws.west}"'}</code>.
          </li>
          <li>
            <strong>Literal versus expression confusion:</strong> <code>module.source</code> is literal text, while
            many resource arguments are expression positions. Generated JSON has to respect that difference.
          </li>
          <li>
            <strong>Overusing JSON syntax:</strong> If the real problem is generating an IAM policy, ECS definition, or
            API payload, keep the Terraform module in HCL and use <code>jsonencode()</code> for that value instead.
          </li>
          <li>
            <strong>Assuming validate works before init:</strong> In fresh environments, run <code>terraform init</code>{" "}
            first so provider plugins and module dependencies are available.
          </li>
        </ul>

        <h2 className="text-2xl font-semibold mt-8">Conclusion</h2>
        <p>
          Terraform JSON configuration is most useful when machines generate it and humans validate it. If your main
          question is provider syntax, remember the split: declare providers in{" "}
          <code>terraform.required_providers</code>, configure them in top-level <code>provider</code> blocks, and
          select specific instances with literal provider addresses like <code>aws.west</code>.
        </p>
        <p>
          That keeps <code>.tf.json</code> files closer to current Terraform behavior, easier to review, and less
          likely to break when they reach <code>terraform init</code>, <code>validate</code>, or <code>plan</code>.
        </p>
      </div>
    </>
  );
}
