name: Desktop Tests

on:
  push:
    branches: [ master ]
    paths:
      - 'desktop/**'
      - 'shared/**'
      - '.github/workflows/desktop-test.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'desktop/**'
      - 'shared/**'
      - '.github/workflows/desktop-test.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: desktop
        
    steps:
    - uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install pnpm
      uses: pnpm/action-setup@v3
      with:
        version: 8
        run_install: false
        
    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
        
    - uses: actions/cache@v4
      name: Setup pnpm cache
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-
          
    - name: Install dependencies
      run: pnpm install
      
    - name: Type check
      run: pnpm exec tsc --noEmit
      
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb libxtst6 libxss1 libgtk-3-0 libnss3 libasound2

    - name: Run tests with xvfb
      run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" pnpm test
      env:
        CI: true
        DISPLAY: :99.0 