name: Release App

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '.github/**'
      - '!.github/workflows/release.yml'
  pull_request:
    types: [closed]
    branches:
      - master
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 1.2.3)'
        required: true
        default: '1.0.0'

permissions:
  contents: write
  pull-requests: write

jobs:
  # This job will only run for PR events
  check-release-pr:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
    outputs:
      is_release_pr: ${{ steps.check.outputs.is_release_pr }}
      version: ${{ steps.check.outputs.version }}
    steps:
      - name: Check if release PR
        id: check
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_BRANCH="${{ github.event.pull_request.head.ref }}"
          
          if [[ "$PR_BRANCH" == *"release-please"* ]] || [[ "$PR_TITLE" == *"release"* ]]; then
            echo "is_release_pr=true" >> $GITHUB_OUTPUT
            VERSION=$(echo "$PR_TITLE" | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' || echo "1.0.0")
            echo "version=$VERSION" >> $GITHUB_OUTPUT
            echo "This is a release PR with version $VERSION"
          else
            echo "is_release_pr=false" >> $GITHUB_OUTPUT
            echo "This is not a release PR"
          fi

  # This job will run for push events and manual triggers
  determine-version:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    outputs:
      version: ${{ steps.get_version.outputs.version }}
      release_created: ${{ steps.release_please.outputs.release_created || steps.manual_version.outputs.release_created }}
      tag_name: ${{ steps.release_please.outputs.tag_name || steps.manual_version.outputs.tag_name }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Release Please
        id: release_please
        if: github.event_name == 'push'
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
          skip-labeling: true
          skip-github-release: false

      - name: Set manual version
        id: manual_version
        if: github.event_name == 'workflow_dispatch'
        run: |
          VERSION="${{ github.event.inputs.version }}"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "release_created=true" >> $GITHUB_OUTPUT
          echo "tag_name=v$VERSION" >> $GITHUB_OUTPUT
          echo "Manually triggered release for version $VERSION"

      - name: Get final version
        id: get_version
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            VERSION="${{ github.event.inputs.version }}"
          elif [[ "${{ github.event_name }}" == "push" ]]; then
            if [[ "${{ steps.release_please.outputs.release_created }}" == "true" ]]; then
              MAJOR="${{ steps.release_please.outputs.major }}"
              MINOR="${{ steps.release_please.outputs.minor }}"
              PATCH="${{ steps.release_please.outputs.patch }}"
              VERSION="${MAJOR}.${MINOR}.${PATCH}"
            else
              VERSION="0.0.0"  # Default if no release was created
            fi
          else
            VERSION="0.0.0"  # Default fallback
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Final version: $VERSION"

  # This decision job determines if we should build and release
  should-build-release:
    runs-on: ubuntu-latest
    needs: [check-release-pr, determine-version]
    if: always()
    outputs:
      should_build: ${{ steps.check.outputs.should_build }}
      version: ${{ steps.check.outputs.version }}
    steps:
      - name: Check build conditions
        id: check
        run: |
          # Default to not building
          echo "should_build=false" >> $GITHUB_OUTPUT
          
          # For manual trigger, always build
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "should_build=true" >> $GITHUB_OUTPUT
            echo "version=${{ needs.determine-version.outputs.version }}" >> $GITHUB_OUTPUT
            echo "Manual trigger - will build version ${{ needs.determine-version.outputs.version }}"
            exit 0
          fi
          
          # For push event with release created by release-please
          if [[ "${{ github.event_name }}" == "push" && "${{ needs.determine-version.outputs.release_created }}" == "true" ]]; then
            echo "should_build=true" >> $GITHUB_OUTPUT
            echo "version=${{ needs.determine-version.outputs.version }}" >> $GITHUB_OUTPUT
            echo "Release created by release-please - will build version ${{ needs.determine-version.outputs.version }}"
            exit 0
          fi
          
          # For PR event with release PR
          if [[ "${{ github.event_name }}" == "pull_request" && "${{ needs.check-release-pr.outputs.is_release_pr }}" == "true" ]]; then
            echo "should_build=true" >> $GITHUB_OUTPUT
            echo "version=${{ needs.check-release-pr.outputs.version }}" >> $GITHUB_OUTPUT
            echo "Release PR merged - will build version ${{ needs.check-release-pr.outputs.version }}"
            exit 0
          fi
          
          echo "No conditions met for building - skipping build"

  # Build for all platforms
  build-platforms:
    needs: [should-build-release]
    if: needs.should-build-release.outputs.should_build == 'true'
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install dependencies
        run: |
          cd desktop
          pnpm install

      - name: Update version in package.json
        run: |
          cd desktop
          VERSION="${{ needs.should-build-release.outputs.version }}"
          node -e "const fs=require('fs');const pkg=JSON.parse(fs.readFileSync('package.json'));pkg.version='$VERSION';fs.writeFileSync('package.json',JSON.stringify(pkg,null,2))"

      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2

      - name: Build for macOS
        if: matrix.os == 'macos-latest'
        run: |
          cd desktop
          pnpm run build -- --mac

      - name: Build for Windows
        if: matrix.os == 'windows-latest'
        run: |
          cd desktop
          pnpm run build -- --win

      - name: Build for Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          cd desktop
          pnpm run build -- --linux

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-${{ matrix.os }}
          path: desktop/release/${{ needs.should-build-release.outputs.version }}/*

  # Create GitHub release with artifacts
  create-release:
    needs: [should-build-release, build-platforms]
    if: needs.should-build-release.outputs.should_build == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: release-artifacts

      - name: Create or update GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ needs.should-build-release.outputs.version }}
          name: Release v${{ needs.should-build-release.outputs.version }}
          files: release-artifacts/**/*
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 