name: Release App

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '.github/**'
      - '!.github/workflows/release.yml'
  pull_request:
    types: [closed]
    branches:
      - master
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 1.2.3)'
        required: true
        default: '1.0.0'

permissions:
  contents: write
  pull-requests: write

jobs:
  # This job will only run for PR events
  check-release-pr:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
    outputs:
      is_release_pr: ${{ steps.check.outputs.is_release_pr }}
      version: ${{ steps.check.outputs.version }}
    steps:
      - name: Check if release PR
        id: check
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_BRANCH="${{ github.event.pull_request.head.ref }}"
          
          if [[ "$PR_BRANCH" == *"release-please"* ]] || [[ "$PR_TITLE" == *"release"* ]]; then
            echo "is_release_pr=true" >> $GITHUB_OUTPUT
            VERSION=$(echo "$PR_TITLE" | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' || echo "1.0.0")
            echo "version=$VERSION" >> $GITHUB_OUTPUT
            echo "This is a release PR with version $VERSION"
          else
            echo "is_release_pr=false" >> $GITHUB_OUTPUT
            echo "This is not a release PR"
          fi

  # This job will run for push events and manual triggers
  determine-version:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    outputs:
      version: ${{ steps.get_version.outputs.version }}
      release_created: ${{ steps.release_please.outputs.release_created || steps.manual_version.outputs.release_created }}
      tag_name: ${{ steps.release_please.outputs.tag_name || steps.manual_version.outputs.tag_name }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Release Please
        id: release_please
        if: github.event_name == 'push'
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
          skip-labeling: true
          skip-github-release: false

      - name: Set manual version
        id: manual_version
        if: github.event_name == 'workflow_dispatch'
        run: |
          VERSION="${{ github.event.inputs.version }}"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "release_created=true" >> $GITHUB_OUTPUT
          echo "tag_name=v$VERSION" >> $GITHUB_OUTPUT
          echo "Manually triggered release for version $VERSION"

      - name: Get final version
        id: get_version
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            VERSION="${{ github.event.inputs.version }}"
          elif [[ "${{ github.event_name }}" == "push" ]]; then
            if [[ "${{ steps.release_please.outputs.release_created }}" == "true" ]]; then
              MAJOR="${{ steps.release_please.outputs.major }}"
              MINOR="${{ steps.release_please.outputs.minor }}"
              PATCH="${{ steps.release_please.outputs.patch }}"
              VERSION="${MAJOR}.${MINOR}.${PATCH}"
            else
              VERSION="0.0.0"  # Default if no release was created
            fi
          else
            VERSION="0.0.0"  # Default fallback
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Final version: $VERSION"

  # This decision job determines if we should build and release
  should-build-release:
    runs-on: ubuntu-latest
    needs: [check-release-pr, determine-version]
    if: always()
    outputs:
      should_build: ${{ steps.check.outputs.should_build }}
      version: ${{ steps.check.outputs.version }}
    steps:
      - name: Check build conditions
        id: check
        run: |
          # Default to not building
          echo "should_build=false" >> $GITHUB_OUTPUT
          
          # For manual trigger, always build
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "should_build=true" >> $GITHUB_OUTPUT
            echo "version=${{ needs.determine-version.outputs.version }}" >> $GITHUB_OUTPUT
            echo "Manual trigger - will build version ${{ needs.determine-version.outputs.version }}"
            exit 0
          fi
          
          # For push event with release created by release-please
          if [[ "${{ github.event_name }}" == "push" && "${{ needs.determine-version.outputs.release_created }}" == "true" ]]; then
            echo "should_build=true" >> $GITHUB_OUTPUT
            echo "version=${{ needs.determine-version.outputs.version }}" >> $GITHUB_OUTPUT
            echo "Release created by release-please - will build version ${{ needs.determine-version.outputs.version }}"
            exit 0
          fi
          
          # For PR event with release PR
          if [[ "${{ github.event_name }}" == "pull_request" && "${{ needs.check-release-pr.outputs.is_release_pr }}" == "true" ]]; then
            echo "should_build=true" >> $GITHUB_OUTPUT
            echo "version=${{ needs.check-release-pr.outputs.version }}" >> $GITHUB_OUTPUT
            echo "Release PR merged - will build version ${{ needs.check-release-pr.outputs.version }}"
            exit 0
          fi
          
          echo "No conditions met for building - skipping build"

  manual-release:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    outputs:
      version: ${{ github.event.inputs.version }}
    steps:
      - name: Set up version
        run: |
          echo "Building version ${{ github.event.inputs.version }}"

  build-windows-linux:
    needs: [manual-release]
    if: github.event_name == 'workflow_dispatch'
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install dependencies
        run: |
          cd desktop
          pnpm install

      - name: Update version in package.json (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          cd desktop
          VERSION="${{ needs.manual-release.outputs.version }}"
          node -e "const fs=require('fs');const pkg=JSON.parse(fs.readFileSync('package.json'));pkg.version='$VERSION';fs.writeFileSync('package.json',JSON.stringify(pkg,null,2))"

      - name: Update version in package.json (Windows)
        if: matrix.os == 'windows-latest'
        shell: powershell
        run: |
          cd desktop
          $VERSION = "${{ needs.manual-release.outputs.version }}"
          $pkgContent = Get-Content -Path package.json -Raw | ConvertFrom-Json
          $pkgContent.version = $VERSION
          $pkgContent | ConvertTo-Json -Depth 100 | Set-Content -Path package.json

      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          # Try best-effort to install dependencies, don't fail if some are missing
          sudo apt-get install -y \
            libgtk-3-dev \
            libwebkit2gtk-4.1-dev || \
          sudo apt-get install -y \
            libgtk-3-dev \
            libwebkit2gtk-4.0-dev || true
          
          # Install other dependencies, continue even if some fail
          sudo apt-get install -y libnss3 libxss1 || true

      - name: Build for Windows
        if: matrix.os == 'windows-latest'
        run: |
          cd desktop
          pnpm run build -- --win

      - name: Build for Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          cd desktop
          pnpm run build -- --linux || true

      - name: Create distributable directory
        run: mkdir -p dist-packages

      - name: Collect Windows packages
        if: matrix.os == 'windows-latest'
        shell: powershell
        run: |
          $VERSION = "${{ needs.manual-release.outputs.version }}"
          
          # Only copy the main distributable files and update metadata
          Get-ChildItem -Path "desktop/release/$VERSION" -Recurse -Include "desktop_*.exe" | Copy-Item -Destination "dist-packages" -Force
          Get-ChildItem -Path "desktop/release/$VERSION" -Recurse -Include "latest.yml" | Copy-Item -Destination "dist-packages" -Force
          
          # List found packages
          echo "Found Windows packages:"
          Get-ChildItem -Path "dist-packages"

      - name: Collect Linux packages
        if: matrix.os == 'ubuntu-latest'
        run: |
          VERSION="${{ needs.manual-release.outputs.version }}"
          
          # Only copy the main distributable files
          find desktop/release/$VERSION -type f -name "desktop-*.AppImage" -exec cp {} dist-packages/ \;
          find desktop/release/$VERSION -type f -name "desktop_*.AppImage" -exec cp {} dist-packages/ \;
          find desktop/release/$VERSION -type f -name "desktop_*.deb" -exec cp {} dist-packages/ \;
          find desktop/release/$VERSION -type f -name "desktop_*.rpm" -exec cp {} dist-packages/ \;
          find desktop/release/$VERSION -type f -name "desktop_*.snap" -exec cp {} dist-packages/ \;
          find desktop/release/$VERSION -type f -name "latest-linux.yml" -exec cp {} dist-packages/ \;
          
          # List found packages
          echo "Found Linux packages:"
          ls -la dist-packages/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-${{ matrix.os }}
          path: dist-packages/
          if-no-files-found: warn

  build-macos-intel:
    needs: [manual-release]
    if: github.event_name == 'workflow_dispatch'
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install dependencies
        run: |
          cd desktop
          pnpm install

      - name: Update version in package.json
        run: |
          cd desktop
          VERSION="${{ needs.manual-release.outputs.version }}"
          node -e "const fs=require('fs');const pkg=JSON.parse(fs.readFileSync('package.json'));pkg.version='$VERSION';fs.writeFileSync('package.json',JSON.stringify(pkg,null,2))"

      - name: Build for macOS Intel (x64)
        run: |
          cd desktop
          pnpm run build:mac-intel

      - name: Create distributable directory
        run: mkdir -p dist-packages-intel

      - name: Collect macOS Intel packages
        run: |
          VERSION="${{ needs.manual-release.outputs.version }}"
          # Copy Intel builds only
          find desktop/release/$VERSION -type f -name "desktop_*-x64.dmg" -exec cp {} dist-packages-intel/ \;
          find desktop/release/$VERSION -type f -name "desktop_*-x64.zip" -exec cp {} dist-packages-intel/ \;
          find desktop/release/$VERSION -type f -name "desktop_*-x64-mac.dmg" -exec cp {} dist-packages-intel/ \;
          find desktop/release/$VERSION -type f -name "desktop_*-x64-mac.zip" -exec cp {} dist-packages-intel/ \;
          # Debug output
          echo "Contents of release directory:"
          ls -la desktop/release/$VERSION/
          # Include auto-update metadata
          find desktop/release/$VERSION -type f -name "latest-mac.yml" -exec cp {} dist-packages-intel/ \;
          
          # List found packages
          echo "Found macOS Intel packages:"
          ls -la dist-packages-intel/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-macos-intel
          path: dist-packages-intel/
          if-no-files-found: warn

  build-macos-arm64:
    needs: [manual-release]
    if: github.event_name == 'workflow_dispatch'
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install dependencies
        run: |
          cd desktop
          pnpm install

      - name: Update version in package.json
        run: |
          cd desktop
          VERSION="${{ needs.manual-release.outputs.version }}"
          node -e "const fs=require('fs');const pkg=JSON.parse(fs.readFileSync('package.json'));pkg.version='$VERSION';fs.writeFileSync('package.json',JSON.stringify(pkg,null,2))"

      - name: Build for macOS Apple Silicon (arm64)
        run: |
          cd desktop
          pnpm run build:mac-m1

      - name: Create distributable directory
        run: mkdir -p dist-packages-arm64

      - name: Collect macOS Apple Silicon packages
        run: |
          VERSION="${{ needs.manual-release.outputs.version }}"
          # Debug output
          echo "Contents of release directory:"
          ls -la desktop/release/$VERSION/
          # Copy arm64 builds only
          find desktop/release/$VERSION -type f -name "desktop_*-arm64.dmg" -exec cp {} dist-packages-arm64/ \;
          find desktop/release/$VERSION -type f -name "desktop_*-arm64.zip" -exec cp {} dist-packages-arm64/ \;
          find desktop/release/$VERSION -type f -name "desktop_*-arm64-mac.dmg" -exec cp {} dist-packages-arm64/ \;
          find desktop/release/$VERSION -type f -name "desktop_*-arm64-mac.zip" -exec cp {} dist-packages-arm64/ \;
          
          # List found packages
          echo "Found macOS Apple Silicon packages:"
          ls -la dist-packages-arm64/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-macos-arm64
          path: dist-packages-arm64/
          if-no-files-found: warn

  create-source-code:
    needs: [manual-release]
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create source code archives
        run: |
          VERSION="${{ needs.manual-release.outputs.version }}"
          echo "Creating source archives for version $VERSION"
          
          # Create a directory for the source archives
          mkdir -p source-archives
          
          # Create ZIP archive - explicitly exclude the source-archives directory
          zip -r "source-archives/desktop-$VERSION-source.zip" . \
            -x "node_modules/*" \
            -x ".git/*" \
            -x "release/*" \
            -x "dist/*" \
            -x "source-archives/*" \
            -x "desktop/release/*" \
            -x "desktop/dist/*" \
            -x "desktop/node_modules/*" \
            -x "landing/node_modules/*" \
            -x "landing/.next/*" \
            -x "*.zip" \
            -x "*.tar.gz"
          
          # Create tarball
          tar \
            --exclude='.git' \
            --exclude='node_modules' \
            --exclude='release' \
            --exclude='dist' \
            --exclude='source-archives' \
            --exclude='desktop/release' \
            --exclude='desktop/dist' \
            --exclude='desktop/node_modules' \
            --exclude='landing/node_modules' \
            --exclude='landing/.next' \
            -czf "source-archives/desktop-$VERSION-source.tar.gz" .
          
          # List created archives
          ls -la source-archives/

      - name: Upload source archives as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: source-archives
          path: source-archives/
          if-no-files-found: warn

  create-github-release:
    needs: [manual-release, build-windows-linux, build-macos-intel, build-macos-arm64, create-source-code]
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: release-artifacts

      - name: List artifacts
        run: |
          echo "All downloaded artifacts:"
          find release-artifacts -type f | sort

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: v${{ needs.manual-release.outputs.version }}
          name: Release v${{ needs.manual-release.outputs.version }}
          body: |
            Release version ${{ needs.manual-release.outputs.version }}
            
            This is a binary release of the desktop application for Windows, macOS, and Linux.
            
            ### Downloads
            
            **Windows:** desktop_${{ needs.manual-release.outputs.version }}.exe
            **macOS:**
            - Intel (x64): desktop_${{ needs.manual-release.outputs.version }}-x64.dmg
            - Apple Silicon (M1/M2): desktop_${{ needs.manual-release.outputs.version }}-arm64.dmg
            **Linux:** desktop-${{ needs.manual-release.outputs.version }}.AppImage or desktop_${{ needs.manual-release.outputs.version }}.deb
            
            Source code archives are also available for developers.
          draft: false
          generate_release_notes: true
          files: release-artifacts/**/*
          fail_on_unmatched_files: false 