name: Test Desktop App

on:
  push:
    branches: [ master ]
    paths:
      - 'desktop/**'
      - 'shared/**'
      - '.github/workflows/test-desktop.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'desktop/**'
      - 'shared/**'
      - '.github/workflows/test-desktop.yml'

jobs:
  test:
    name: Test Desktop Application
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: desktop
        
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install pnpm
      uses: pnpm/action-setup@v3
      with:
        version: 10
        run_install: false
        
    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
        
    - name: Setup pnpm cache
      uses: actions/cache@v4
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('desktop/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-
          
    - name: Install dependencies
      run: pnpm install
      
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb libxtst-dev libpng-dev libxss-dev libgtk-3-0 libnss3 libasound2t64

    - name: Create screenshots directory
      run: mkdir -p test/screenshots
      
    - name: Run tests with xvfb
      run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" pnpm test
      env:
        CI: true
        DISPLAY: ':99.0'
        
    - name: Upload test screenshots on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: test-screenshots
        path: desktop/test/screenshots
        if-no-files-found: ignore 